# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primary_backup_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprimary_backup_server.proto\x12\x13primarybackupserver\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\x0cRequestReply\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x16\n\x0erequest_status\x18\x02 \x01(\x05\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"\x9e\x01\n\x07Message\x12)\n\x06sender\x18\x01 \x01(\x0b\x32\x19.primarybackupserver.User\x12\x30\n\rdestinataries\x18\x02 \x03(\x0b\x32\x19.primarybackupserver.User\x12\x0c\n\x04text\x18\x03 \x01(\t\x12(\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xd0\x02\n\x13PrimaryBackupServer\x12G\n\x07NewUser\x12\x19.primarybackupserver.User\x1a!.primarybackupserver.RequestReply\x12J\n\nDeleteUser\x12\x19.primarybackupserver.User\x1a!.primarybackupserver.RequestReply\x12Q\n\x0e\x45nqueueMessage\x12\x1c.primarybackupserver.Message\x1a!.primarybackupserver.RequestReply\x12Q\n\x0e\x44\x65queueMessage\x12\x1c.primarybackupserver.Message\x1a!.primarybackupserver.RequestReplyBH\n$io.grpc.examples.PrimaryBackupServerB\x18PrimaryBackupServerProtoP\x01\xa2\x02\x03PBSb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'primary_backup_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$io.grpc.examples.PrimaryBackupServerB\030PrimaryBackupServerProtoP\001\242\002\003PBS'
  _REQUESTREPLY._serialized_start=85
  _REQUESTREPLY._serialized_end=138
  _USER._serialized_start=140
  _USER._serialized_end=164
  _MESSAGE._serialized_start=167
  _MESSAGE._serialized_end=325
  _PRIMARYBACKUPSERVER._serialized_start=328
  _PRIMARYBACKUPSERVER._serialized_end=664
# @@protoc_insertion_point(module_scope)
